version: '3.7'

services:
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - app-data:/var/www/akaunting
    restart: unless-stopped

  php:
    build: ./php
    volumes:
      - app-data:/var/www/akaunting
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: hypriot/rpi-mysql
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: akaunting_root_password
      MYSQL_DATABASE: akaunting_db
      MYSQL_USER: akaunting_admin
      MYSQL_PASSWORD: akaunting_password

  # fix_permissions:
  #   build: ./php
  #   command: chown -R www-data:www-data /var/www/akaunting
  #   volumes:
  #     - app-data:/var/www/akaunting
  #   depends_on:
  #     - php

#   wpsite:
volumes:
  app-data:
  db-data:
